mysql:
  host: localhost
  port: 3306
  username: root
  password:
  database: bound

bind:
  zone_export_path: /etc/bind/zones
  zone_clauses_file: /etc/bind/named.conf.zones
  commands:
    reload: /etc/init.d/bind9 reload
    check_config: named-checkconf /etc/bind/named.conf

rails:
  environment: production
  # Replace this key with a new random key. You can generate one using
  # `bundle exec rake secret` from the root of the application
  secret_key: ad1a6538c2b3cb4f231fad413898ce6144712232b24676d13879eb8704c61fe23b5f8e41e7a519498a8c78c2a95875412052f76e202bf6af9e7394a13d1eb8f8

auth:
  strategy: atech
  description: aTech Identity
  client_key: xx
  client_secret: xx
  scopes: null

smtp:
  host: localhost
  username: null
  password: null
  from_address: Bound <bound@example.com>

web:
  protocol: http
  host: localhost:3000

web_server:
  bind_address: 0.0.0.0
  port: 3000
  max_threads: 5

dns_defaults:
  primary_ns: dns1.example.com
  email_address: hostname@example.com
  refresh_time: 3600
  retry_time: 120
  expiration_time: 2419200
  max_cache: 600
  ttl: 3600
  nameservers:
    - dns1.example.com.
    - dns2.example.com.
    - dns3.example.com.
